name: Deploy build and deploy to Azure through CI/CD pipeline

on: 
  push:
    branches: [main] 
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: emsproject25
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: '7.0.x'   

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x']
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET version ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}       
      - name: Restore project dependencies
        run: dotnet restore ./MKsEMS.csproj         
      - name: Build
        run: dotnet build ./MKsEMS.csproj --configuration Release --no-restore    
      - name: publish
        run: dotnet publish ./MKsEMS.csproj --configuration Release --no-build --no-restore --output ./publish

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SECRETE }}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:          
          app-name: ${{ env.AZURE_WEBAPP_NAME }} 
          publish-profile: ${{ secrets.EMS_APP_PUBLISH }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
          
          
          
          
          
          
          
          



